on:
  push:
    paths:
      - 'data-raw/**'
name: process-data-raw

jobs:
  process-data-raw:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: Rscript -e 'install.packages("stringr")'

      - name: Process data-raw
        run: |
          source("R/describe_text.R")
          source("R/create_vignette.R")
          source("R/clean_up.R")
          source("R/process_data_raw.R")
          process_data_raw()
        shell: Rscript {0}


      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit results
        run: |
          git add -A && git commit -m 'Process data-raw' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
